apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.telemetrySinkService.name }}
  labels:
    app: telemetry-sink
spec:
  selector:
    matchLabels:
      app: telemetry-sink
  template:
    metadata:
      labels:
        app: telemetry-sink
    spec:
      containers:
        - name: telemetry-sink
          image: 93catdog/telemetry-sink:demo # change 'latest' to a specific version for production
          imagePullPolicy: IfNotPresent
          env:
            - name: GRPC_SERVER_SOCKET
              # This variable should tell the gRPC server to listen on all interfaces at the specified port.
              value: "0.0.0.0:{{ .Values.grpcServer.port }}"
          envFrom:
            - configMapRef:
                name: telemetry-sink-env # Reference to a ConfigMap containing environment variables
          ports:
            - containerPort: 8000 # Port the application listens on inside the container
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
