apiVersion: v1
kind: Service
metadata:
  name: telemetry-sink-service
  labels:
    app: telemetry-sink
spec:
  selector:
    app: telemetry-sink
  ports:
    - protocol: TCP
      port: {{ .Values.grpcServer.port }}
      targetPort: {{ .Values.grpcServer.port }}
